config/routes.rb
Rails.application.routes.draw do
  root 'concierge_services#index'

  resources :concierge_services, only: :index
  
  resources :reservations, only: [:new, :create, :show, :destroy] do
    member do
      get 'print_ticket'
      get 'print_lockers'
    end
    collection do
      get 'search'
      get 'searching'
      get 'valid_number'
    end
  end

  get '/customers/valid_identifier', to: 'customers#valid_identifier'
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  scope :checked_in, -> { where(checked_in: true) }
  scope :room_order, -> { order(:room_number) }

  has_many :reservations, dependent: :destroy

  validates :first_name,  presence: true
  validates :last_name,   presence: true
  validates :room_number, presence: true
  validates :checked_in,  inclusion: { in: [true, false] }

  def self.from_identifier identifier
    id = identifier.split("|").last.to_i
    Customer.find_by(id: id)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def identifier
    "#{room_number}, #{full_name} | #{id}"
  end
end

app/models/locker.rb
class Locker < ActiveRecord::Base
  scope :unassigned, -> { where(assigned: false) }
  scope :large,      -> { where(size: "LARGE") }
  scope :medium,     -> { where(size: "MEDIUM") }
  scope :small,      -> { where(size: "SMALL") }

  belongs_to :reservation

  validates :number, presence: true, uniqueness: { case_sensitive: false }
  validates :size, presence: true
  validates :assigned, inclusion: { in: [true, false] }

  def self.lockers_left
    unassigned_lockers = Locker.unassigned
    large_left  = unassigned_lockers.large.count
    medium_left = unassigned_lockers.medium.count
    small_left  = unassigned_lockers.small.count
    
    { large: large_left, medium: medium_left, small: small_left }
  end

  def self.max_bags_allowed
    left = Locker.lockers_left

    { large: left[:large], medium: left[:large] + left[:medium], 
      small: left[:large] + left[:medium] + left[:small] }
  end
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  include ActiveModel::Validations

  attr_accessor :bags_owner, :small, :medium, :large

  scope :number_order, -> { order(:number) }

  belongs_to :customer
  has_many :lockers

  validates :number, presence: true, uniqueness: { case_sensitive: false }
  validates_with ReservationValidator

  before_validation :set_reservation_number, on: :create
  before_create     :set_customer
  before_create     :assign_lockers
  before_destroy    :unassign_lockers



  private



  def set_reservation_number
    caps = ('A'..'Z').to_a
    loop do
      self.number = "-#{Faker::Number.number(4)}"
      3.times { self.number = caps.sample + self.number }
      break unless Reservation.exists?(number: self.number)
    end
  end

  def set_customer
    self.customer = Customer.from_identifier(self.bags_owner)
  end

  def assign_lockers
    left = Locker.lockers_left
    assign_large(left)
    assign_medium(left)
    assign_small(left)
  end

  def assign_large left
    large_requested = self.large.to_i
    assigned = Locker.unassigned.large.limit(large_requested)
    add_assigned_lockers(assigned)
    left[:large] -= large_requested
  end

  def assign_medium left
    medium_requested = self.medium.to_i
    # If more medium lockers are requested than are available, assign
    # the extras to large lockers before continuing and assigning
    # all the medium lockers
    if medium_requested > left[:medium]
      self.large = medium_requested - left[:medium]
      medium_requested = left[:medium]
      assign_large(left)
    end
    assigned = Locker.unassigned.medium.limit(medium_requested)
    add_assigned_lockers(assigned)
    left[:medium] -= medium_requested
  end

  def assign_small left
    small_requested = self.small.to_i
    # If more small lockers are requested than are available, assign
    # the extras to medium lockers before continuing and assigning
    # all the small lockers (if the medium lockers are insufficient,
    # then large lockers will ultimately be assigned).
    if small_requested > left[:small]
      self.medium = small_requested - left[:small]
      small_requested = left[:small]
      assign_medium(left)
    end
    assigned = Locker.unassigned.small.limit(small_requested)
    add_assigned_lockers(assigned)
    left[:small] -= small_requested
  end

  def add_assigned_lockers assigned
    assigned.each { |locker| locker.update_attributes(assigned: true) }
    self.lockers << assigned
  end

  def unassign_lockers
    self.lockers.each do |locker|
      locker.update_attributes(assigned: false, reservation_id: nil)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concierge_services_controller.rb
class ConciergeServicesController < ApplicationController
  def index
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def valid_identifier
    valid = !Customer.from_identifier(params[:reservation][:bags_owner]).nil?
    render json: valid
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def new
    @reservation = Reservation.new
    @max_bags_allowed = Locker.max_bags_allowed
  end

  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      redirect_to @reservation, notice: "Reservation Made. "\
        "Please receive #{@reservation.customer.first_name}'s bag(s)."
    else
      @max_bags_allowed = Locker.max_bags_allowed
      render 'new'
    end
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def destroy
    Reservation.find(params[:id]).destroy
    redirect_to root_path
  end

  def search
  end

  def searching
    @reservation = Reservation.
                     find_by(number: params[:reservation_number].upcase)
    if @reservation
      redirect_to @reservation, notice: "Please return "\
        "#{@reservation.customer.first_name}'s bag(s)."
    else
      flash.now[:error] = "No Reservation Found. "\
        "Please search from list provided."
      render 'search'
    end
  end

  def print_ticket
    @reservation = Reservation.find(params[:id])
  end

  def print_lockers
    @reservation = Reservation.find(params[:id])
  end

  def valid_number
    valid = !Reservation.
               find_by(number: params[:reservation_number].upcase).nil?
    render json: valid
  end


  private


  def reservation_params
    params.require(:reservation).permit(:bags_owner, :small,
                                        :medium,     :large)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title title
    title.blank? ? "UT Hotel" : "#{ title } | UT Hotel"
  end
end

app/views/concierge_services/index.html.haml
- provide(:title, "Concierge Services")

.home
  %h1 Concierge Services

  .left-link
    = link_to "Receive Bag(s)", new_reservation_path

  .right-link
    = link_to "Return Bag(s)", search_reservations_path

app/views/layouts/_flash.html.haml
- if flash.any?
  .row-container
    .flash-holder
      - flash.each do |type, message|
        .flash{ class: "#{type}" }= message

app/views/layouts/_header.html.haml
%header
  .row-container
    = link_to root_path do
      .main-logo
        .initials-holder
          .initials UT
        .rest Hotel
    = link_to concierge_services_path do
      .concierge-logo
        %div Concierge Services
        

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title= page_title(yield(:title))
    = stylesheet_link_tag    'application', media: 'all', 
                             'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = favicon_link_tag 'favicon.ico'

  %body{class: "#{ controller_name } #{ action_name }"}
    .global-holder

      = render "layouts/header"

      .content-container
        = render "layouts/flash"

        .row-container
          .main-container
            = yield

        / = debug(params) if Rails.env.development?

app/views/reservations/_continue.html.haml
.no-print
  = link_to "Continue", @reservation
  

app/views/reservations/_lockers.html.haml
.lockers
  %p
    = "#{ 'Locker'.pluralize @reservation.lockers.count } for reservation "
    %strong= "#{ @reservation.number }"

  - lockers = @reservation.lockers
  %ul
    - if lockers.large.exists?
      %li= lockers.large.order(:number).pluck(:number).join(", ") 
    - if lockers.medium.exists?
      %li= lockers.medium.order(:number).pluck(:number).join(", ")
    - if lockers.small.exists?
      %li= lockers.small.order(:number).pluck(:number).join(", ")

app/views/reservations/_ticket.html.haml
%p.ticket
  = "Reservation Number: "
  %strong= "#{ @reservation.number }"

app/views/reservations/_validation_errors.html.haml
- if @reservation.errors.any?
  .validation-errors
    %p= "Reservation could not be made because of the following: "
    %ul
      - @reservation.errors.full_messages.each do |message|
        %li= message
        

app/views/reservations/new.html.haml
- provide(:title, "Make Reservation")

.new-reservation
  %h2 Receive Bag(s)

  = render "validation_errors"

  .new-form
    = form_for @reservation do |f|
      .form-row
        = f.label :bags_owner, "Bag's Owner"
        = f.search_field :bags_owner, list: 'customers', 
                                placeholder: "RoomNumber, Name"
        %datalist#customers
          - Customer.checked_in.room_order.each do |customer|
            %option{value: "#{customer.identifier}"}

      %p Number of bags
      .form-row
        = f.label :large
        = f.number_field :large,  in: 0..@max_bags_allowed[:large],  step: 1

        = f.label :medium
        = f.number_field :medium, in: 0..@max_bags_allowed[:medium], step: 1

        = f.label :small
        = f.number_field :small,  in: 0..@max_bags_allowed[:small],  step: 1

      = f.submit "Make Reservation"

app/views/reservations/print_lockers.html.haml
- provide(:title, "Reservation Lockers")

= render "lockers"

= render "continue"

app/views/reservations/print_ticket.html.haml
- provide(:title, "Reservation Ticket")

= render "ticket"

= render "continue"

app/views/reservations/search.html.haml
- provide(:title, "Find Reservation")

.search-reservations
  %h2 Return Bag(s)

  .search-form
    = form_tag(searching_reservations_path, id: 'search_reservations', 
                                            method: :get) do
      .form-row
        = label_tag :reservation_number, "Reservation Number"
        = search_field_tag(:reservation_number, params[:reservation_number], 
                            list: 'reservation-numbers')
        %datalist#reservation-numbers
          - Reservation.all.number_order.each do |reservation|
            %option{value: "#{reservation.number}"}

      = submit_tag "Find Reservation"

app/views/reservations/show.html.haml
- provide(:title, "Reservation")

.show-reservation
  %h2= "Reservation for #{ @reservation.customer.full_name }"

  = render "ticket"

  = render "lockers"

  .left-link.top-link
    = link_to "Print Ticket", print_ticket_reservation_path(@reservation)
  .right-link.top-link
    = link_to "Print Lockers ", print_lockers_reservation_path(@reservation)

  %br

  .left-link
    = link_to "Bag(s) Received", root_path, class: 'alt-link'
  .right-link
    = link_to "Bag(s) Returned", @reservation, method: :delete, 
                                 class: 'danger-link'